[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
rocket = "0.5.0-rc.2"
reqwest = { version = "0.11.10", json = true }
tokio-postgres = "0.7.6"
